FROM jupyter/minimal-notebook
LABEL maintainer="Maxim Letunov" \
      ffmpeg="3.2.4" \
      opencv="3.2.0" \
      jupyter="python 2.7, python 3.5, scala" \
      version="3.0"

USER root

COPY ffmpeg_3.2.4-1_amd64.deb opencv_3.2.0-1_amd64.deb /tmp/
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && apt-get -y upgrade \
    && apt-get install -y --no-install-recommends curl nodejs \
    && (dpkg -i /tmp/ffmpeg_3.2.4-1_amd64.deb || (apt-get install -fy && dpkg -i /tmp/ffmpeg_3.2.4-1_amd64.deb)) \
    && (dpkg -i /tmp/opencv_3.2.0-1_amd64.deb || (apt-get install -fy && dpkg -i /tmp/opencv_3.2.0-1_amd64.deb)) \
    && ldconfig \
    && rm /tmp/*.deb \
    && rm -rf /var/lib/apt/lists/*

# install java
ENV LANG=C.UTF-8 JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
COPY java.sh /tmp
RUN chmod +x /tmp/java.sh && sync && /tmp/java.sh && rm /tmp/java.sh

USER $NB_USER

# install extensions
RUN conda install -c damianavila82 rise \
    && jupyter-nbextension install rise --py --sys-prefix \
    && jupyter-nbextension enable rise --py --sys-prefix

# install kernels
RUN wget -O coursier https://git.io/vgvpD && chmod +x coursier && sync \
    && wget -O scala.sh https://git.io/vrHhi && chmod +x scala.sh && sync \
    && ./scala.sh \
    && rm coursier && rm scala.sh \
    && conda install nodejs \
    && conda config --add channels r \
    && conda install --quiet --yes \
    'r-base=3.3.2' \
    'r-irkernel=0.7*' \
    'r-plyr=1.8*' \
    && conda clean -tipy

# install python3 kernel packages
RUN ln -s $CONDA_DIR/bin/pip $CONDA_DIR/bin/pip3 \
    && pip3 install --upgrade pip \
    && pip3 install numpy pillow pandas tensorflow matplotlib keras edward