FROM jupyter/tensorflow-notebook
LABEL maintainer="Maxim Letunov" \
      ffmpeg="3.2.2" \
      opencv="3.2.0" \
      python="2.7,3.5" \
      jupyter="python,scala" \
      version="2.0"

# upgrade python packages in conda
RUN conda install -y -n root numpy tensorflow matplotlib keras && \
    conda install -y -n root -c danim edward && \
    conda install -y -n python2 numpy tensorflow matplotlib keras && \
    conda install -y -n python2 -c danim edward

USER root

# prepare debian
COPY init.sh /tmp
RUN cd /tmp && chmod +x init.sh && sync && ./init.sh && rm init.sh

# install ffmpeg 3.2.2
ARG ffmpeg=http://www.ffmpeg.org/releases/ffmpeg-3.2.2.tar.gz
COPY ffmpeg.sh /tmp
RUN cd /tmp && chmod +x ffmpeg.sh && sync && ./ffmpeg.sh $ffmpeg && rm ffmpeg.sh

# install opencv 3.2.0
ARG opencv=https://github.com/opencv/opencv/archive/3.2.0.tar.gz
COPY opencv.sh /tmp
RUN cd /tmp && chmod +x opencv.sh && sync && ./opencv.sh $opencv && rm opencv.sh

RUN rm /tmp/*.deb

# install java
COPY java.sh /tmp
RUN cd /tmp && chmod +x java.sh && sync && ./java.sh && rm java.sh

USER $NB_USER

# install scala kernel to jupyter
RUN curl -L -o jupyter-scala https://git.io/vrHhi && chmod +x jupyter-scala && ./jupyter-scala && rm -f jupyter-scala