FROM jupyter/tensorflow-notebook
LABEL maintainer="Maxim Letunov" \
      ffmpeg="3.2.4" \
      opencv="3.2.0" \
      jupyter="python 2.7, python 3.5, scala" \
      version="3.0"

USER root

COPY ffmpeg_3.2.4-1_amd64.deb opencv_3.2.0-1_amd64.deb /tmp/
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && apt-get -y upgrade \
    && (dpkg -i /tmp/ffmpeg_3.2.4-1_amd64.deb || (apt-get install -fy && dpkg -i /tmp/ffmpeg_3.2.4-1_amd64.deb)) \
    && (dpkg -i /tmp/opencv_3.2.0-1_amd64.deb || (apt-get install -fy && dpkg -i /tmp/opencv_3.2.0-1_amd64.deb)) \
    && ldconfig \
    && rm /tmp/*.deb \
    && rm -rf /var/lib/apt/lists/*

# install java
ENV LANG=C.UTF-8 JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
COPY java.sh /tmp
RUN chmod +x /tmp/java.sh && sync && /tmp/java.sh && rm /tmp/java.sh

USER $NB_USER

# install scala kernel to jupyter and packages to python
RUN wget -O coursier https://git.io/vgvpD && chmod +x coursier && sync \
    && wget -qO- https://git.io/vrHhi | sed 's/coursier/.\/coursier/' | sh \
    && rm coursier \
    && conda install -y -n root numpy tensorflow matplotlib keras \
    && conda install -y -n root -c danim edward \
    && conda install -y -n python2 numpy tensorflow matplotlib keras \
    && conda install -y -n python2 -c danim edward